### ISSUE TITLE
Rewrite TestProbeWhitelist e2e test

### ISSUE THREAD

**Issue by nak3** [knative-sandbox/net-istio#135]
related to https://github.com/knative/net-istio/issues/132 and https://github.com/knative/serving/issues/7507

[Istio 1.6](https://istio.io/news/releases/1.6.x/announcing-1.6/upgrade-notes/#support-ended-for-v1alpha1-security-policy) does not support `v1alpha1 authentication policy`.

Although it could be replaced with `v1beta1 RequestAuthentication`, the new RequestAuthentication does not support regex feature for now. Please refer to - https://github.com/istio/istio/issues/16585#issuecomment-603565983.

The current [TestProbeWhitelist](https://github.com/knative/serving/blob/6e6e43cb39d7fab108d15f0b10e2c886619cde1b/test/e2e/probe_whitelist_test.go#L38) highly depends on [the regex](https://github.com/knative/serving/blob/6e6e43cb39d7fab108d15f0b10e2c886619cde1b/test/config/security/policy.yaml#L39-L55), so we need to re-write it.

**Comment by nak3** [comment]
FYI @itsmurugappan

**Comment by itsmurugappan** [comment]
Thanks @nak3 I can work on it. /assign @itsmurugappan

**Comment by itsmurugappan** [comment]
@nak3 we were not using regex in the tests
