### ISSUE TITLE
The webhook must be excluded from the mesh

### ISSUE THREAD

**Issue by JRBANCEL** [knative-sandbox/net-istio#150]
Currently, if Istio sidecar injection is enabled on `knative-serving` namespace, the webhook will also have a sidecar.
Given that the `MutatingWebhookConfiguration` specifies an expected CA for the certificate exposed by the webhook endpoint, a component outside of the mesh (e.g. `kube-api`) fails to contact the webhook when the sidecar tries to terminate the TLS connection, which happens in mTLS strict mode (in permissive mode, Envoy acts a TCP proxy, see https://github.com/istio/istio/blob/master/pilot/pkg/networking/core/v1alpha3/listener.go#L211):
- sidecar + Webhook + mTLS permissive = OK
- sidecar + Webhook + mTLS strict = FAILS
- just Webhook + mTLS permissive = OK
- just Webhook + mTLS strict = OK

The webhook is designed to only be contacted by `kube-api` (outside of the mesh) and to not contact anything, therefore, it should always be excluded from the mesh:
```
kubectl patch deployments.apps -n knative-serving webhook -p '{"spec":{"template":{"metadata":{"annotations":{"sidecar.istio.io/inject":"false"}}}}}'
```

/cc @Cynocracy

**Comment by nak3** [comment]
@JRBANCEL
I agree. We should set injection `false` for webhook.
I (optimistically) assumed that we can set the namespace to permissive mode, but just got the feedback to use STRICT as https://github.com/knative/docs/issues/1130#issuecomment-645593574 yesterday.

**Comment by vagababov** [comment]
Is this more or less generic annotation or it's istio specific?
Since we might need to to the same in some other places. Gloo, e.g.?

**Comment by nak3** [comment]
It is istio specific annotation. The `networking-istio` deployment already has it  https://github.com/knative/net-istio/blob/master/config/controller.yaml#L34. So I think we don't need the annotation for other Ingress but only for istio.

**Comment by JRBANCEL** [comment]
> Since we might need to to the same in some other places. Gloo, e.g.?
All webhooks need it, including the `knative/serving` one.

**Comment by vagababov** [comment]
My question was more towards what's the annotation to use for other meshes
vs istio only.

**Comment by JRBANCEL** [comment]
The annotation is definitely not portable across platforms.

**Comment by tshak** [comment]
I'm the one who made the comment about STRICT mode. It's a concern since auditing tools like Twistlock will probably not be happy to see even part of the mesh in PERMISSIVE mode. I don't claim to be an Istio expert by any means. It'd be great to have some feedback from the Istio team on this.

**Comment by JRBANCEL** [comment]
> I'm the one who made the comment about STRICT mode. It's a concern since auditing tools like Twistlock will probably not be happy to see even part of the mesh in PERMISSIVE mode.

What is your concern?
This work is to make it possible to run Knative with mTLS *STRICT*.
That's what you want, right?

**Comment by tshak** [comment]
I apologize for not being clear. You are correct that STRICT for all namespaces is the goal. I was commenting on the original guidance which was to use PERMISSIVE mode in the `knative-serving` namespace. It appears as though that the recommendation has been changed in favor of removing istio injection from the webhook pods.

**Comment by JRBANCEL** [comment]
I see. I am not sure that the goal is having everything be part of the mesh with mTLS strict, especially Webhooks since they are separate from the rest of the components (only `kube-api` calls the Webhook).
Now, I am not familiar with the typical security requirements, so maybe we should actually aim for that.
I'll explore keeping the Webhook inside the mesh and see if it possible for `kube-api` to reach it using a Gateway and a VirtualService.

**Comment by tshak** [comment]
The issue with PERMISSIVE in `knative-serving` is that this could potentially (I haven't proven it) open up a hole where a non-mesh service could get access to the mesh somehow. Essentially, anything communicating with services on the mesh must be on the mesh themselves. I'm in agreement with the approach of moving webhooks outside of the mesh . I don't see any benefit of them running in the mesh since they're just communicating with the Kube API.

**Comment by JRBANCEL** [comment]
> I'm in agreement with the approach of using STRICT mode on the `knative-serving` namespace and moving webhooks outside of the mesh . I can't think of any security benefit of them running in the mesh since they're just communicating with the Kube API.

There are some benefits of being part of the mesh (i.e. having a sidecar injected) without really using the mesh part (as in the mTLS, peer-to-peer part) that can be used by Webhooks:
- unified logging/auditing of requests
- unified metrics reporting
- integration with some tools/dashboards

**Comment by JRBANCEL** [comment]
I explored a couple options.

## Do not inject the sidecar
This is done with an annotation.
### Pros
Simple.
### Cons
How to annotate webhooks outside of this repository, such as `serving`?
No sidecar = no metrics, auditing, logs, compliance, etc...

## Use mTLS Permissive for Webhooks 
```
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "webhook-policy"
  namespace: "knative-serving"
spec:
  selector:
    matchLabels:
      app: webhook
  mtls:
    mode: PERMISSIVE
```
### Pros
Simple and we can have an object in `net-istio` applying to the Webhook in `serving`.
Sidecar = metrics, auditing, logs, compliance, etc...
### Cons
Ideally, everything is mTLS STRICT

## Have `kube-api` requests go through a Gateway
This requires a Gateway
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: webhook-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
    hosts:
    - webhook.knative-serving.svc
```
And a matching VirtualService.
I haven't managed to have a fully working example.
### Pros
mTLS STRICT everywhere.
### Cons
It is convoluted (requires to modify the Webhook registrations), adds indirection and little value.

**Comment by tshak** [comment]
Great writeup. Regarding the first con:

> No sidecar = no metrics, auditing, logs, compliance

I'd be curious from other folks running Istio if they are typically running webhooks on the mesh.  I'm not aware of any specific security requirement around running this type of traffic on the mesh. I believe that the TLS security between kube and webhooks is already sufficient and not prone to problems that a mesh typically mitigates such as developer misconfiguration of TLS. I'd love to hear from others running Istio in the wild on this.

**Comment by JRBANCEL** [comment]
> > No sidecar = no metrics, auditing, logs, compliance
> 
> I'd be curious from other folks running Istio if they are typically running webhooks on the mesh. I'm not aware of any specific security requirement around running this type of traffic on the mesh. I believe that the TLS security between kube and webhooks is already sufficient and not prone to problems that a mesh typically mitigates such as developer misconfiguration of TLS. I'd love to hear from others running Istio in the wild on this.

I think you are correct, in the case of the Webhook, the value of a sidecar is not security as Envoy will be configured as a simple TCP proxy in this case (external caller -> mesh node with mTLS PERMISSIVE). But you still get the rest: metrics, logs, traffic graph, etc... that Istio mesh provides.

**Comment by tshak** [comment]
I agree that there are possible benefits, I'm just curious if those benefits are being realized in practice. Prior to Knative, I never would have thought to run admission/mutating webhooks on mesh.

**Comment by nak3** [comment]
How about this?

- Release manifest ... does not add `sidecar.istio.io/inject=false`.
- Tests(e2e)       ... excludes webhook from the mesh by `kubectl patch` and test with mTLS strict mode.
- Doc              ... writes both how to exclude and include webhook from/in the mesh and use mTLS.

We should assume that we will not be able to add istio annotation to core component as https://github.com/knative/serving/issues/6421.

The cons is that we will miss the e2e tests of webhook with sidecar, but I think that excluding the webhook from the mesh & mTLS strict mode is more strict tests so we could compromise it.

**Comment by tshak** [comment]
I would add: 

- The Operator must add `sidecar.istio.io/inject=false` to all webhooks

We should not patch operator managed resources as that patch is not guaranteed to stick.
