### ISSUE TITLE
Support different Ingress Service types

### ISSUE THREAD

**Issue by manuelstein** [knative-sandbox/net-istio#168]
AFAICS, only the LoadBalancer-type Ingressgateway service is currently supported. When Istio is installed with ingressgateway type NodePort or ClusterIP, the ingress gw status.loadbalancer field remains empty "{}" (k8s 1.16.4) and the Knative routes don't reconcile and are stuck with the Ready status set to "Unknown" and the reason "Uninitialized". A static IP can only be set if the cloud controller manager supports it (Azure). Other setups may use virtual IP routing in which case the ingress gateway service would have externalIPs configured. Or it may use NodePort in which case it would be nice if the ingress endpoint could be configured statically in config-istio for the istio-webhook not to depend on a LB type ingressgateway service.

IIRC older versions may have supported the NodePort type.
Wdyt? Best, Manuel

**Comment by tcnghia** [comment]
@manuelstein did you see a problem when using NodePort? If so, can you please post the problem you saw here?

**Comment by manuelstein** [comment]
I was trying to recreate the error and I think what happened is that the Service had been created with LoadBalancer first and additional runs to deploy the manifest had failed to update the Service which is immutable when it comes to changing its type and type-specific parameters.
