### ISSUE TITLE
Probing optimization take 2

### ISSUE THREAD

**Issue by mattmoor** [knative-sandbox/net-istio#188]
_This is the net-istio side of https://github.com/knative/serving/issues/8765._

Currently the network probing logic implements an optimization where a pod is assumed to have been fully programmed once any part of the network programming we are probing has been successfully verified.  In practice, this means that for each pod we are enqueuing N pieces of work and cancelling N-1 pieces of work for each gateway pod every time we change a kingress.

Given that this builds on a faulty assumption (in the linked issue), I'd propose instead optimizing this on the net-istio side here:

https://github.com/knative-sandbox/net-istio/blob/56f23ab0d69625e409602c9bd56c9de07f008142/pkg/reconciler/ingress/lister.go#L105

Instead of enqueuing N pieces of work per pod, and then cancelling the N-1 pieces of work, simply choose one piece of work to verify (per IP) and prune the rest.  This should achieve what the prober-side optimization yields and more because this should also improve the throughput of the prober workqueue.

I'd like to avoid having Istio take a hit to correct the issue above, and this should be safe to start in isolation, so if anyone wants to try and knock this off I'd appreciate it. 🙏 

cc @JRBANCEL @tcnghia @vagababov

**Comment by JRBANCEL** [comment]
> Instead of enqueuing N pieces of work per pod, and then cancelling the N-1 pieces of work, simply choose one piece of work to verify (per IP) and prune the rest.

This assume that any `host` will eventually return 200.

I am not 100% sure but I think this might be an issue because we might try to probe a `host` that is not going to be in the `Ingress` (because of internal/external hosts). Let me check.

/assign

**Comment by mattmoor** [comment]
@JRBANCEL haven't cracked Istio's invocation in a while, but on the Contour side I'm partitioning the hosts by visibility, so I'd expect all probes to succeed.  LMK if you want to chat about it and we can figure it out (I'm out next week tho!).

**Comment by JRBANCEL** [comment]
I am pretty sure that's what is done on the Istio side as well, but I haven't looked at this code in a while.

**Comment by JRBANCEL** [comment]
I thought we were using the hosts defined in `Gateway.Spec.Servers[].Host` (as reported in https://github.com/knative-sandbox/net-istio/issues/68 (third item)) but it is not the case anymore. The hosts are coming from the Ingress object, so it should be fine to pick a random one.
