### ISSUE TITLE
grpc streams timeout

### ISSUE THREAD

**Issue by itsmurugappan** [knative-sandbox/net-istio#202]
### knative version 

0.15

### Issue

I am able to create a unidirectional grpc stream server as ksvc successfully. But the stream gets terminated by timeout set on istio virtual service. This time out by default is set to the max revision time out value.

### Steps To Recreate

Create a unidirectional grpc stream server (where client receives the stream), deploy it as ksvc. 
Have the ksvc timeout less than the max revision timeout, have the grpc server send the stream continuously and you will notice that after the max revision timeout the client will receive a RST_STREAM error.

Since the queue proxy times out after the time mentioned in ksvc, is it necessary for the istio virtual service to have timeout set. Is it ok to remove it ? @nak3 @tcnghia @ZhiminXiang

**Comment by vagababov** [comment]
This was fixed and then rolled back
/cc @mattmoor

**Comment by tcnghia** [comment]
This should be fixed by https://github.com/knative/networking/pull/64

**Comment by itsmurugappan** [comment]
> This should be fixed by https://github.com/knative/networking/pull/64 

Thanks a lot.
