### ISSUE TITLE
Remove cluster-local-gateway Deployment

### ISSUE THREAD

**Issue by JRBANCEL** [knative-sandbox/net-istio#212]
The details are in this [doc](https://docs.google.com/document/d/1kqGPwEeo2uNfZlVlS3wZNeCiGakRxTXuclz9rehw9j8/).

This is to track the rollout. The current plan to have 0 downtime is:

## Phase 1
1) Add a `server` entry to `cluster-local-gateway` on port 8081 (no-op just makes the Envoy listen on this port)

🕐  Wait for Istio propagation

## Phase 2
2) Modify the `cluster-local` `Service` `targetPort` to `8081` (k8s will route internal traffic to the new port) 
3) Remove the original `server` entry in `cluster-local-gateway` (port 80 is not used anymore)
4) Update the selector of the `Gateway` to select both `Deployment` (Ingress and Cluster Local)

🕐 : Wait for Istio propagation

## Phase 3
5) Modify the `cluster-local` `Service` to select the Ingress `Deployment`
5) Update the selector of the `Gateway` to select only the Ingress `Deployment`

:clock1: Wait for Istio propagation

## Phase 4
6) Delete Cluster Local `Deployment` 

This could be done in a single release by waiting for propagation before proceeding to the next steps where required, or we can spread it over multiple releases. @tcnghia any thoughts?

/assign

**Comment by tcnghia** [comment]
My inclination is to avoid staging over multiple releases: we can get result faster and even allow N+2 upgrades without issue.

**Comment by JRBANCEL** [comment]
Ok, let me see how much of a downtime it would be we do all the changes at the same time.
It should be minimal and less error prone. Also, it is for internal traffic only so less visible for external calls.

**Comment by JRBANCEL** [comment]
I am writing a migration job. It is simpler and safer.

**Comment by JRBANCEL** [comment]
Phase 3 is done: #411 
/close
