### ISSUE TITLE
Istio uninstallation cleans up Gateway created by net-istio.yaml

### ISSUE THREAD

**Issue by nak3** [knative-sandbox/net-istio#218]
This might be an issue in operation not net-istio, but I report the issue here as a Knative user was confused.

### Issue description

- If we uninstalled Istio, Gateway (cluster-local-gateway, knative-ingress-gateway) in knative-serving namespace also gone as `istioctl` deletes CRD.

#### 1. Install istio by following [doc](https://knative.dev/docs/install/installing-istio/)

```
$ istioctl manifest apply -f istio-minimal-operator.yaml
````

#### 2. Install Knative Serving and net-istio

```
$ kubectl apply --filename https://storage.googleapis.com/knative-nightly/serving/latest/serving-crds.yaml
$ kubectl apply --filename https://storage.googleapis.com/knative-nightly/serving/latest/serving-core.yaml
$ kubectl apply --filename https://storage.googleapis.com/knative-nightly/net-istio/latest/release.yaml
```

#### 3. Knative app works fine

```
$ kn service create hello-example --image=gcr.io/knative-samples/helloworld-go

$ kubectl port-forward -n istio-system service/istio-ingressgateway  8000:80
Forwarding from 127.0.0.1:8000 -> 8080
Forwarding from [::1]:8000 -> 8080
Handling connection for 8000

$ curl -H "Host: hello-example.default.example.com" localhost:8000
Hello World!
```

#### 4. Re-installing Istio

Do not touch Knative, but just re-install Istio.

```
$ istioctl manifest generate -f istio-minimal-operator.yaml | kubectl delete -f -
$ istioctl manifest apply -f istio-minimal-operator.yaml
```

#### 5. Knative becomes unreachable

Now, Knative app started unreachable.

- port-forward starts producing following error

```
$ kubectl port-forward -n istio-system service/istio-ingressgateway  8000:80
Forwarding from 127.0.0.1:8000 -> 8080
Forwarding from [::1]:8000 -> 8080
Handling connection for 8000
E0813 15:22:23.690783    4348 portforward.go:400] an error occurred forwarding 8000 -> 8080: error forwarding port 8080 to pod fb1991564571888471fc564b2a2fe08f528fea1ceeafe99db8fef57f4564a310, uid : exit status 1: 2020/08/13 06:22:23 socat[199389] E connect(5, AF=2 127.0.0.1:8080, 16): Connection refused
Handling connection for 8000
```

- Access gets `Empty reply from server`.

```
$ curl -H "Host: hello-example.default.example.com" localhost:8000
curl: (52) Empty reply from server
```

### Root cause of this issue

This is because Gateway in knative-serving ns was deleted in step-4. We need to re-install Gateways in net-istio.yaml.

```
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: knative-ingress-gateway
  namespace: knative-serving
  labels:
    serving.knative.dev/release: "v20200811-4a3c487"
    networking.knative.dev/ingress-provider: istio
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: cluster-local-gateway
  namespace: knative-serving
  labels:
    serving.knative.dev/release: "v20200811-4a3c487"
    networking.knative.dev/ingress-provider: istio
spec:
  selector:
    istio: cluster-local-gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
EOF
```

I wonder that Gateway (cluster-local-gateway, knative-ingress-gateway) should not be included in net-istio.yaml, but net-istio controller should create it if not exist.

**Comment by tshak** [comment]
> I wonder that Gateway (cluster-local-gateway, knative-ingress-gateway) should not be included in net-istio.yaml, but net-istio controller should create it if not exist.

Yes. Another scenario where this becomes a problem is when managing knative with gitops: 

- The gitops controller applies `net-istio.yaml`, which in turn creates the knative `Gateway` resources
- The `net-istio` controller mutates the `Gateway` resources (e.g. adding TLS information for a `ksvc`). 
- At some point in the near future, the gitops controller re-applies `net-istio.yaml`. This may clobber mutations made by  the `net-istio` controller. 

Also note that upgrading `net-istio` by applying a new version of the `net-istio.yaml` manifest can have the same effect. This is because some mutations (in my case TLS configuration as part of `cert-namespace`) are not compatible with a patch-strategic-merge. Therefore, I believe that the lifecycle of all `Gateway` resources should be managed by the `net-istio` controller and should not be included in `net-istio.yaml`.

**Comment by nak3** [comment]
Thank you so much @tshak That is great input.
