### ISSUE TITLE
Fix 503s error on Istio 1.5 or later installed by istioctl 

### ISSUE THREAD

**Issue by nak3** [knative-sandbox/net-istio#254]
This is a tracking issue for the 503 issue in Istio 1.5 (installed by `istioctl`).
Currently Istio upgrade got stuck due to 503 error. https://github.com/istio/istio/issues/23029 is discussing with Istio team and has some detail.

obsolete tickets: https://github.com/knative/serving/issues/8210 https://github.com/knative/serving/issues/8193

**Comment by tcnghia** [comment]
@nak3 this can be closed, right?

**Comment by nak3** [comment]
Yes, I think we can close this.
