### ISSUE TITLE
Investigate the Automatic Protocol Selection feature of Istio 1.3

### ISSUE THREAD

**Issue by tanzeeb** [knative-sandbox/net-istio#27]
## In what area(s)?

/area API
/area networking

## Describe the feature

Istio 1.3 supports ["Automatic Protocol Selection"](https://istio.io/docs/ops/traffic-management/protocol-selection/#automatic-protocol-selection), meaning we might not have to specify container port names to support `http` and `http2`.

This issue is to track the investigation of that feature.

Notes:
* We will need to support Istio versions prior to 1.3 until they are end of life'd, [approx. 3 months](https://istio.io/about/release-cadence/).
* We may not need to update the [Ports and Protocols](https://github.com/knative/serving/blob/master/docs/runtime-contract.md#protocols-and-ports) section of the runtime contract after all (cc @dgerd )

cc @tcnghia @mattmoor 
/assign

**Comment by tcnghia** [comment]
I tried this but doesn't work. Also @igorbelianski and @rafaeltello are working on another solution for the same goal.

/close
