### ISSUE TITLE
install-istio.sh should support NodePort `istio-ingressgateway`

### ISSUE THREAD

**Issue by tcnghia** [knative-sandbox/net-istio#285]
In here https://github.com/knative/serving/pull/9301 we propose to use `install-istio.sh` for development purpose. 

Supporting NodePort will help those of us who are using `Minikube` or `KinD`. This will also make it easier to run integration tests using `net-istio` on GitHub Actions.

cc @mattmoor @JRBANCEL

**Comment by JRBANCEL** [comment]
What does support `NodePort` mean?
I use `minkube` a lot and I do this:
```
$ minikube start --cpus 6 --memory 20000 --driver=kvm2
$ cd $GOPATH/src/knative.dev/net-istio
$ ./third_party/istio-latest/install-istio.sh istio-ci-no-mesh.yaml
$ cat <<EOF | kubectl apply -f -     
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http2
      protocol: HTTP2
    hosts:
    - "*"
EOF
$ minikube service istio-ingressgateway -n istio-system
|--------------|----------------------|--------------------------------|--------------------------------|
|  NAMESPACE   |         NAME         |          TARGET PORT           |              URL               |
|--------------|----------------------|--------------------------------|--------------------------------|
| istio-system | istio-ingressgateway | status-port/15021 http2/80     | http://192.168.39.172:30633    |
|              |                      | https/443 tls/15443            | http://192.168.39.172:31595    |
|              |                      |                                | http://192.168.39.172:32438    |
|              |                      |                                | http://192.168.39.172:30688    |
|--------------|----------------------|--------------------------------|--------------------------------|
$ curl http://192.168.39.172:31595 -v
> GET / HTTP/1.1
> Host: 192.168.39.172:31595
> User-Agent: curl/7.64.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< date: Wed, 16 Sep 2020 06:24:40 GMT
< server: istio-envoy
< content-length: 0
```

**Comment by mattmoor** [comment]
When you change `type: LoadBalancer` to `type: NodePort`, you hit the node's IP and each port tuple contains a `nodePort` you can address on that node IP.  Essentially for:
```
- name: http
  port: 80
  nodePort: 9876
  targetPort: 1234
- name: https
  port: 443
  nodePort: 7564
  targetPort: 2345
```

Basically when you `curl http://foo.example.com` the dialer gets `foo.example.com:80` and we decompose this and *actually* dial `192.168.39.172:9876`.  For `curl https://foo.example.com` the dialer gets `foo.example.com:443` and we *actually* dial `192.168.39.172:7564`.

Right now `--ingressendpoint` is how we get `192.168.39.172`

**Comment by JRBANCEL** [comment]
What I was trying to demonstrate is that minikube can expose any type of k8s Service using the same mechanism of port mapping. This seemed cleaner than having to change the Service type.

But it is minikube specific and I am now aware of Matt's recent change in spoofing that requires `Spec.Ports.NodePort` to be specified. The cleanest way to address this for `install-istio.sh` is to have a custom profile specifying the Service type.

/assign
