### ISSUE TITLE
istio virtualservice-ingress with retries as 0

### ISSUE THREAD

**Issue by fahadsuhaib** [knative-sandbox/net-istio#296]
Hi,

We are seeing unwanted retries due to 500 status code by the service, and this is annoying as it is running in a serverless environment and the error had to be immediately propagated back.

Need to add the below code to https://github.com/knative-sandbox/net-istio/blob/524afbe8aa70b5589360d0e96b92ef2cd8c6a317/pkg/reconciler/ingress/resources/virtual_service.go#L221,
```
Retries: &istiov1alpha3.HTTPRetry{
				Attempts:      0,
				PerTryTimeout: nil,
			},

```

This is a very bad situation to be in, as the actual service is returning error but we are retrying it for 3 times before returning the response.

**Comment by JRBANCEL** [comment]
We do not set the `HTTPRetry` field since https://github.com/knative-sandbox/net-istio/pull/263.
The behavior you are describing will be in the next release.

**Comment by fahadsuhaib** [comment]
Perfect @JRBANCEL, When is the next release scheduled for?

**Comment by nak3** [comment]
The next release (v0.18) is scheduled next week. You can find the schedule here https://github.com/knative/pkg/blob/master/RELEASE-LEADS.md#schedule
