### ISSUE TITLE
Document perf regression of 1.5

### ISSUE THREAD

**Issue by tcnghia** [knative-sandbox/net-istio#311]
There is a noticeable regression in 1.5 that was fixed in 1.7 (and possibly 1.6).

This should be documented (with links to bugs) on knative.dev so users are aware.

**Comment by tcnghia** [comment]
cc @ZhiminXiang @JRBANCEL hopefully this should be done before doc release

**Comment by JRBANCEL** [comment]
What details are you expecting?
We should just recommend using 1.7.x, no?

**Comment by tcnghia** [comment]
Yes, at the minimum we should advise 1.7. But mentioning that 1.5, 1.6 work but not well & links to issue would be awesome too.
