### ISSUE TITLE
Getting "resource name may not be empty" when installing with `third_party/istio-stable/istio-minimal.yaml`

### ISSUE THREAD

**Issue by taragu** [knative-sandbox/net-istio#351]
I'm getting an error "resource name may not be empty" when installing with `third_party/istio-stable/istio-minimal.yaml`.
```
kubectl apply -f "https://raw.githubusercontent.com/knative-sandbox/net-istio/master/third_party/istio-stable/istio-minimal.yaml"
error: error when retrieving current configuration of:
Resource: "install.istio.io/v1alpha1, Resource=istiooperators", GroupVersionKind: "install.istio.io/v1alpha1, Kind=IstioOperator"
Name: "", Namespace: "default"
Object: &{map["kind":"IstioOperator" "spec":map["addonComponents":map["pilot":map["enabled":%!q(bool=true)] "prometheus":map["enabled":%!q(bool=false)]] "components":map["ingressGateways":[map["enabled":%!q(bool=true) "name":"istio-ingressgateway"] map["enabled":%!q(bool=true) "k8s":map["service":map["ports":[map["name":"status-port" "port":'\u3aac'] map["name":"http2" "port":'P' "targetPort":'\u1f90'] map["name":"https" "port":'\u01bb' "targetPort":'\u20fb']] "type":"ClusterIP"]] "label":map["app":"cluster-local-gateway" "istio":"cluster-local-gateway"] "name":"cluster-local-gateway"]]] "values":map["global":map["useMCP":%!q(bool=false) "jwtPolicy":"first-party-jwt" "proxy":map["autoInject":"disabled"]]]] "metadata":map["namespace":"default" "annotations":map["kubectl.kubernetes.io/last-applied-configuration":""]] "apiVersion":"install.istio.io/v1alpha1"]}
from server for: "https://raw.githubusercontent.com/knative-sandbox/net-istio/master/third_party/istio-stable/istio-minimal.yaml": resource name may not be empty
```
Also the serving development instructions (https://github.com/knative/serving/blob/master/DEVELOPMENT.md#deploy-istio) need to be updated, since we no longer have `third_party/istio-stable/istio-crds.yaml`.

**Comment by nak3** [comment]
@taragu Thank you for the report.
As @ZhiminXiang updated in https://github.com/knative-sandbox/net-istio/pull/357, current istio manifest needs `istioctl` command. So ccould you please use `third_party/istio-latest/install-istio.sh` (wrapper script) to install it?

For serving development instructions, it is also still working in progress here https://github.com/knative/serving/pull/9301. Sorry if it caused you any trouble.

**Comment by taragu** [comment]
@nak3 thanks for the update!

**Comment by nak3** [comment]
net-istio's DEVELOPMENT.md now suggests that we use  [`third_party/istio-latest/install-istio.sh`](https://github.com/knative-sandbox/net-istio/blob/master/DEVELOPMENT.md#install-istio ).
serving repo's DEVELOPMENT.md was updated by https://github.com/knative/serving/pull/9301.

I think we can close this issue. @taragu please feel free to re-open if you have found any other issue.
