### ISSUE TITLE
Remove config-autoscale dependency from controller & webhook

### ISSUE THREAD

**Issue by tcnghia** [knative-sandbox/net-istio#36]

**Comment by tcnghia** [comment]
Looks like the dependency is here

https://github.com/knative/serving/blob/master/pkg/apis/config/store.go#L23

and

https://github.com/knative/net-istio/blob/master/cmd/webhook/main.go#L62

**Comment by tcnghia** [comment]
cc @mattmoor ^

**Comment by vagababov** [comment]
At some point I got rid of it, but then it got re-introduced for initial scale. I don't think we can get rid of it right now.
net-istio no longer seems to depend on it
/close

**Comment by vagababov** [comment]
well, it's not in net istio at all :)
