### ISSUE TITLE
E2E tests are failing for net-istio

### ISSUE THREAD

**Issue by VIjayHP** [knative-sandbox/net-istio#439]
Command : 
Error: TestIstioProbing/HTTP: spoof.go:171: Retrying http://istio-probing-http-txschmyn.example.com/: retrying for DNS error: Get "http://istio-probing-http-txschmyn.example.com/": dial tcp: lookup <istio-ingressgateway-ip:port>: no such host 
**Following pods are running under knative-serving namespace:**
activator-845748699b-v7xmz 1/1 Running 1 6d2h
autoscaler-696d8868f4-vrnrp 1/1 Running 0 6h29m
autoscaler-hpa-6b98f6459f-7rthf 1/1 Running 0 45s
chaosduck-598c45795f-jwsbg 1/1 Running 0 6h27m
controller-7f7566fbcb-659j8 1/1 Running 0 45s
istio-webhook-7dd7c94c7b-hdffn 1/1 Running 1 5d21h
networking-istio-85f6b5c894-5n4x7 1/1 Running 1 5d21h
webhook-54d6f984b4-bg544 1/1 Running 1 6d2h

**Following pods are running under istio-system namespace:**
grafana-8d9455fd-zqbpd                    1/1     Running     0          32h
istio-citadel-5bf656946d-s2jqg            1/1     Running     0          32h
istio-cleanup-secrets-1.1.7-qgtqp         0/1     Completed   0          32h
istio-egressgateway-687fbb67c7-9wsd2      1/1     Running     0          32h
istio-galley-f8c5f49f9-nzbtv              1/1     Running     0          32h
istio-grafana-post-install-1.1.7-7llt4    0/1     Completed   3          32h
istio-ingressgateway-844867fd4d-vdzrb     1/1     Running     0          21m
istio-init-crd-10-94spv                   0/1     Completed   0          32h
istio-init-crd-11-ls9jj                   0/1     Completed   0          32h
istio-init-crd-certmanager-10-n7qv7       0/1     Completed   0          32h
istio-init-crd-certmanager-11-l5mkf       0/1     Completed   0          32h
istio-pilot-974f569dd-6jvmg               2/2     Running     0          32h
istio-policy-6f67b6ddfd-k5xfv             2/2     Running     4          32h
istio-security-post-install-1.1.7-glhdm   0/1     Completed   0          32h
istio-sidecar-injector-664b7959cf-vk5lh   1/1     Running     0          32h
istio-telemetry-77b8d9994d-lz45t          2/2     Running     4          32h
istio-tracing-5dd567bc89-dq6cx            1/1     Running     0          32h
kiali-79995c85d5-8q9c7                    1/1     Running     0          32h
prometheus-54cfb94449-c2gpd               1/1     Running     0          32h
Command : go test -v -timeout=0m -tags=e2e -count=1 ./test/e2e --dockerrepo <my-insecure-docker-repo> --ingressendpoint <istio-ingressgateway-ip:port>

Will net-istio support's pulling test images from Insecure private docker registry?

**Comment by VIjayHP** [comment]
Could someone help me with the above failures or any additional setup/procedure I need to follow for running e2e tests for net-istio?

**Comment by nak3** [comment]
What did you specify for `-- --ingressendpoint ` ? As per your message `dial tcp: lookup istio-ingressgateway-ip:port: no such host` you didn't specify the IP and port correctly.

**Comment by VIjayHP** [comment]
Hi, I am adding "--ingressendpoint" flag due to  istio-ingressgateway is exposed as node port service and it's accessible with clusterip:nodeport . Should i need to run the e2e test's without this flag ?   @nak3

**Comment by nak3** [comment]
`dial tcp: lookup istio-ingressgateway-ip:port: no such host` is clearly saying that the DNS resolution failed. Could you solve this DNS error first? It seems your env issue. it is strange for me why DNS error happens even though the IP address was specified in the option.

**Comment by VIjayHP** [comment]
@nak3 
Is it possible to run the E2E tests without that flag ?
$Command : go test -v -timeout=0m -tags=e2e -count=1 ./test/e2e --dockerrepo <private-insecure-registry>
 
Will it work in this way?

**Comment by nak3** [comment]
If you are using service with ClusterIP, it is possible. But you are using NodePort, aren't you? Then you need to use the flag.

**Comment by VIjayHP** [comment]
@nak3 Yes i don't have any external-ip service , i am using cluster-ip:nodeport here
