### ISSUE TITLE
unable to recognize "https://github.com/knative/net-istio/releases/download/v0.19.0/release.yaml": no matches for kind "PeerAuthentication" in version "security.istio.io/v1beta1"

### ISSUE THREAD

**Issue by VIjayHP** [knative-sandbox/net-istio#440]
After running the below command :
kubectl apply --filename https://github.com/knative/net-istio/releases/download/v0.19.0/release.yaml

**Error:**
unable to recognize "https://github.com/knative/net-istio/releases/download/v0.19.0/release.yaml": no matches for kind "PeerAuthentication" in version "security.istio.io/v1beta1"
unable to recognize "https://github.com/knative/net-istio/releases/download/v0.19.0/release.yaml": no matches for kind "PeerAuthentication" in version "security.istio.io/v1beta1"

**Comment by nak3** [comment]
Did you install Istio before running the `kubectl apply` command? If yes, what istio version did you use?
The error should not happen if you install Istio v1.7.x beforehand.

**Comment by VIjayHP** [comment]
Hi @nak3 yes all the below pods are running under "istio-system" namespace
grafana-8d9455fd-zqbpd                    1/1     Running     0          4d2h
istio-citadel-5bf656946d-s2jqg            1/1     Running     0          4d2h
istio-cleanup-secrets-1.1.7-qgtqp         0/1     Completed   0          4d2h
istio-egressgateway-687fbb67c7-9wsd2      1/1     Running     0          4d2h
istio-galley-f8c5f49f9-nzbtv              1/1     Running     0          4d2h
istio-grafana-post-install-1.1.7-7llt4    0/1     Completed   3          4d2h
istio-ingressgateway-844867fd4d-v2t8d     1/1     Running     0          5m10s
istio-init-crd-10-94spv                   0/1     Completed   0          4d2h
istio-init-crd-11-ls9jj                   0/1     Completed   0          4d2h
istio-init-crd-certmanager-10-n7qv7       0/1     Completed   0          4d2h
istio-init-crd-certmanager-11-l5mkf       0/1     Completed   0          4d2h
istio-pilot-974f569dd-6jvmg               2/2     Running     0          4d2h
istio-policy-6f67b6ddfd-k5xfv             2/2     Running     4          4d2h
istio-security-post-install-1.1.7-glhdm   0/1     Completed   0          4d2h
istio-sidecar-injector-664b7959cf-vk5lh   1/1     Running     0          4d2h
istio-telemetry-77b8d9994d-lz45t          2/2     Running     4          4d2h
istio-tracing-5dd567bc89-dq6cx            1/1     Running     0          4d2h
kiali-79995c85d5-8q9c7                    1/1     Running     0          4d2h
prometheus-54cfb94449-c2gpd               1/1     Running     0          4d2h

And i am using v1.1.7 version of istio and https://github.com/istio/istio/releases/download/1.2.2/istio-1.2.2-linux.tar.gz
in order to install istio using helm way (install/kubernetes/helm/istio). 
Which version of istio i need to use ? any suggestion's on this?

**Comment by VIjayHP** [comment]
@nak3 1.7.1 version of istio doesn't comes with helm way of installation here: install/kubernetes/helm/istio (got 404 page for this https://github.com/istio/istio/tree/1.7.1/install/kubernetes/helm/istio) .Kindly let me know helm way of installation if i need to use other version's as i am doing it on ppc64le architecture .

**Comment by JRBANCEL** [comment]
`PeerAuthentication` v1beta1 was introduced in Istio 1.5.
You'll need to use at least that version or more recent or simply ignore this (it is only useful for mTLS).

**Comment by VIjayHP** [comment]
@JRBANCEL But the status of Knative Serving Custom Resource is false due to the above issue :
After installing the Knative Operator custom resource i see below issue for the command:
$ kubectl get KnativeServing knative-serving -n knative-serving
**Error:**
Events:
  Type     Reason           Age                   From                       Message
  ----     ------           ----                  ----                       -------
  Normal   FinalizerUpdate  6m17s                 knativeserving-controller  Updated "knative-serving" finalizers
  Warning  InternalError    2m5s (x16 over 6m6s)  knativeserving-controller  failed to apply non rbac manifest: no matches for kind "PeerAuthentication" in version "security.istio.io/v1beta1"

**Comment by VIjayHP** [comment]
@JRBANCEL Do we have any dependency with this Peer Authentication issue for E2E testing ?

Above 2 resources are not created because of my **Istio version (1.1.7)** . However while performing E2E tests for net-istio it get's stucked here:

**Pre-Requisite :**
root@vijay1:~# kubectl get po -n knative-serving
NAME                                READY   STATUS        RESTARTS   AGE
chaosduck-6b658d579d-dzmrc          1/1     Running       0          17h
istio-webhook-9b89b85c7-49q6d       1/1     Terminating   0          45s
istio-webhook-9b89b85c7-rn8tp       1/1     Running       0          23s
networking-istio-5787575595-864wn   1/1     Running       0          23s
root@vijay1:~# kubectl get po -n serving-tests
NAME                           READY   STATUS    RESTARTS   AGE
istio-probing-http-fsvueuub    1/1     Running   0          17h
istio-probing-http2-gydxpasp   1/1     Running   0          17h

$ go test -race -count=1 -short -timeout=20m -tags=e2e ./test/e2e --enable-alpha --enable-beta --dockerrepo <docker-repo> --ingressendpoint <hostname -i> --ingressClass=istio.ingress.networking.knative.dev

 stream.go:248: E 06:36:42.577 networking-istio-5787575595-nskh7 [istio-ingress-controller] [serving-tests/istio-probing-http2-gydxpasp] Probing of http://istio-probing-http2-gydxpasp.example.com:80 failed, IP: 10.x.x.x:80, ready: false, error: unexpected status code: want 200, got 404 (depth: 0)
    stream.go:248: I 06:36:42.628 networking-istio-5787575595-nskh7 [istio-ingress-controller] [serving-tests/istio-probing-http2-gydxpasp] Processing probe for http://istio-probing-http2-gydxpasp.example.com:80, IP: 10.x.x.x:80 (depth: 0)

**Comment by JRBANCEL** [comment]
> @JRBANCEL Do we have any dependency with this Peer Authentication issue for E2E testing ?

Only if you use mTLS in STRICT mode.

```
stream.go:248: E 06:36:42.577 networking-istio-5787575595-nskh7 [istio-ingress-controller] [serving-tests/istio-probing-http2-gydxpasp] Probing of http://istio-probing-http2-gydxpasp.example.com:80 failed, IP: 10.x.x.x:80, ready: false, error: unexpected status code: want 200, got 404 (depth: 0)
```

404 is expected when the service is created. Does it not go away after some time (couple seconds)?

**Comment by VIjayHP** [comment]
> `PeerAuthentication` v1beta1 was introduced in Istio 1.5.
> You'll need to use at least that version or more recent or simply ignore this (it is only useful for mTLS).

But in case of running tests for Knative-Operator , because of the above issue "custom resource" fails to come TRUE state.
Error: with the error message: Install failed with message: no matches for kind "PeerAuthentication" in version "security.istio.io/v1beta1"

So how can we ignore this in knative-operator , As it is creating by default.

**Comment by nak3** [comment]
> So how can we ignore this in knative-operator , As it is creating by default.

One possible workaround is that you can create the  `PeerAuthentication` CRD. For example, I think you can create the CRD from here  https://github.com/istio/istio/blob/41c366ab7ac32085ec95b93528c5b53e4dca9c8b/manifests/charts/base/crds/crd-all.gen.yaml#L3242-L3334

But anyway Istio 1.1.x is too old. We haven't tested the old version with the latest Knative/net-istio.
