### ISSUE TITLE
Run mesh conformance tests as part of PR process

### ISSUE THREAD

**Issue by arturenault** [knative-sandbox/net-istio#461]
Recently we let a pretty [egregious istio bug](https://github.com/istio/istio/issues/29566) slip into istio-latest which breaks all of knative when sidecars are injected.

We should run a small subset of mesh tests as part of PRs to avoid this. Conformance tests should be enough.

/area test-and-release

**Comment by tcnghia** [comment]
We have https://github.com/knative-sandbox/net-istio/issues/136 opened, can I assign it to you @arturenault ?

**Comment by arturenault** [comment]
Sure, I think these are slightly different though. Looks like we need to add a mesh test environment in the first place, and then have it run as part of the PR process. Up to you if this needs two different items though

**Comment by arturenault** [comment]
Close as duplicate; turns out we already support mesh tests but aren't running them.
