### ISSUE TITLE
Pull in istio canonical label strings from istio/api

### ISSUE THREAD

**Issue by trshafer** [knative-sandbox/net-istio#47]
Upon the next release of istio/api, update the istio dependency and replace the canonical labels with the ones added in https://github.com/istio/api/pull/1339

**Comment by tcnghia** [comment]
This is blocked by #51

**Comment by tcnghia** [comment]
#51 is fixed by #52

**Comment by trshafer** [comment]
Thoughts on pulling from master instead of a release? I think since this was added after 1.5.0 was released, we should wait until 1.6 or 1.5.1 is released to pull those strings in.

**Comment by tcnghia** [comment]
I don't feel comfortable about pulling from master... Given that we've already inlined the strings here ourselves, the benefit is small compared to risk.

**Comment by trshafer** [comment]
Cool. I'll just wait.

**Comment by trshafer** [comment]
Fixed by https://github.com/knative-sandbox/net-istio/pull/127
