### ISSUE TITLE
e2e test for mesh mode with istio-latest is broken

### ISSUE THREAD

**Issue by nak3** [knative-sandbox/net-istio#477]
Please refer to https://testgrid.knative.dev/serving#istio-latest-mesh. The mesh mode with istio-latest is broken now.

stable-mesh is not broken as https://testgrid.knative.dev/serving#istio-stable-mesh, so it would be related to VirtualService status or istio version?

/cc @JRBANCEL @arturenault @ZhiminXiang

**Comment by arturenault** [comment]
It's the Istio version, I opened this Istio issue about it:

https://github.com/istio/istio/issues/29566

**Comment by howardjohn** [comment]
Can you check with 1.8.2? This should be fixed

**Comment by arturenault** [comment]
I have a PR out to use 1.8.2. Once that's merged we'll know if the fix is good: #486

**Comment by arturenault** [comment]
1.8.2 seems to have solved the issue.

/close
