### ISSUE TITLE
Run tests against Istio HEAD

### ISSUE THREAD

**Issue by arturenault** [knative-sandbox/net-istio#496]
The Istio team is interested in us testing against their HEAD to ensure we catch issues that break us early. We can ensure maximum test coverage by running our tests against Istio HEAD. This should be straightforward by adding a new `istio-head` folder that installs istio from HEAD.

/cc @howardjohn @ZhiminXiang 

/assign

**Comment by costinm** [comment]
We also want to have a test that runs a Istiod revision as a KNative service - so Istiod revisions can be scaled to zero and installed as easily as any knative service. That's assuming KNative is using a fixed/dedicated istiod ( or something else ), and the Istiods are  used by tenants or namespaces that want dedicated control plane revisions.

I have a set of changes to enable this mode, and Istio Env WG seems ok to evaluate this mode of istiod deployment.

**Comment by vagababov** [comment]
How much benefit using HEAD vs Nightly are we getting vs one more testgrid to run and operate?
Or we just want to have possibility of installing istio from head?

**Comment by costinm** [comment]
From Istio perspective - the goal is to make sure Istio mater doesn't break something. Doesn't have to be Istio head or KNative head - nightly or weekly is fine, just faster than the ~3 month release cycle we have in Istio.

**Comment by vagababov** [comment]
Sure, that's one of the reasons we run against nightly.

**Comment by howardjohn** [comment]
What is the "nightly"? I thought there was istio-latest (ie 1.8.x) and istio-stable (1.7.x) - both are released versions. Running from HEAD would allow us to find breakages before we release something, rather than weeks after

**Comment by vagababov** [comment]
cc @JRBANCEL , but I think this is this: https://github.com/knative-sandbox/net-istio/tree/master/third_party/istio-latest

**Comment by vagababov** [comment]
My understanding is that we download and run CICD with the latest released istio whenever that is released on github.

**Comment by howardjohn** [comment]
Right, the desire is that if we send a commit to Istio master today, it would be first released in Istio 1.10 in ~4 months. it would be ideal to know today that we broke Knative (or improved :slightly_smiling_face: ), rather than 4 months from now

**Comment by vagababov** [comment]
OK, I guess it's nightly build of `net-istio` :) my misunderstanding.
Then, yeah — in total support 👍
