### ISSUE TITLE
Investigate and switch to Istio v1beta1 API

### ISSUE THREAD

**Issue by tcnghia** [knative-sandbox/net-istio#50]
We should take a look at the new Istio v1beta1 API

https://github.com/istio/api/commits/master/networking/v1beta1

if it is ready for use, we should start a feature track to migrate to Istio v1beta1.

**Comment by howardjohn** [comment]
Its the same API with a new label for `beta`. We don't have any conversion webhook or anything so they are identical

**Comment by tcnghia** [comment]
@howardjohn when do you plan to turn down the v1alpha3 API?  I'd love to wait until 1.4 is phased out, so both supported Istio versions (1.5, 1.6) speak v1beta1.

For existing  VirtualServices, would it be ok to have a short time when both v1beta1 VirtualService and v1alpha3 VirtualService exist?  I am paranoid about removing the v1alpha3 VirtualService before the corresponding v1beta1 VirtualService is working properly.

**Comment by howardjohn** [comment]
Using alpha is identical to using beta at this point. We have not started doing anything like conversion webhooks, the APIs are identical now and the move was to symbolize stability more than anything. In the future this may change but that is the current state at least for 1.6

**Comment by howardjohn** [comment]
So staying on alpha is fine
