### ISSUE TITLE
Istio Authorization - RBAC: access denied and Error roundtripping http://*:80/healthz: context deadline exceeded

### ISSUE THREAD

**Issue by evankanderson** [knative-sandbox/net-istio#555]
From https://github.com/knative/serving/issues/10688

@muthurajr

I'm trying to add end user authentication for Istio (version=1.7.1) which doesn't work for services deployed through Knative(version=0.20.0). Getting error "RBAC: access denied" while trying to test the deployed service.

[ root@curl:/ ]$ curl --header "Authorization: Bearer $TOKEN" --header "Host: hello.iteration1.example.com" "$INGRESS_HOST"
RBAC: access denied
[ root@curl:/ ]$ curl --header "Authorization: Bearer $TOKEN" "$INGRESS_HOST/iteration1/hellovs"
RBAC: access denied

Steps followed to create a sample application and validate are attached in the file. Seems like I'm missing some authorization which enables the health check. Any help on the same?

[knative.txt](https://github.com/knative/serving/files/5919774/knative.txt)

Activator Log:
{"severity":"WARNING","timestamp":"2021-02-03T15:50:59.304263555Z","logger":"activator","caller":"net/revision_backends.go:286","me
ssage":"Failed probing pods","commit":"560a4f6","knative.dev/controller":"activator","knative.dev/pod":"activator-b75d6b66c-7tlkz",
"knative.dev/key":"iteration1/hello-00001","curDests":{"ready":"","notReady":"10.173.192.23:8012"},"error":"**error roundtripping htt
p://10.173.192.23:8012/healthz: dial tcp 10.173.192.23:8012: connect: connection refused**","logging.googleapis.com/labels":{},"loggi
ng.googleapis.com/sourceLocation":{"file":"knative.dev/serving/pkg/activator/net/revision_backends.go","line":"286","function":"kna
tive.dev/serving/pkg/activator/net.(*revisionWatcher).checkDests"}}
{"severity":"ERROR","timestamp":"2021-02-03T15:50:59.604539236Z","logger":"activator","caller":"net/revision_backends.go:322","mess
age":"**Failed to probe clusterIP 10.173.223.137:80**","commit":"560a4f6","knative.dev/controller":"activator","knative.dev/pod":"activ
ator-b75d6b66c-7tlkz","knative.dev/key":"iteration1/hello-00001","error":"**error roundtripping http://10.173.223.137:80/healthz: con
text deadline exceeded**","logging.googleapis.com/labels":{},"logging.googleapis.com/sourceLocation":{"file":"knative.dev/serving/pkg
/activator/net/revision_backends.go","line":"322","function":"knative.dev/serving/pkg/activator/net.(*revisionWatcher).checkDests"}
,"stacktrace":"knative.dev/serving/pkg/activator/net.(*revisionWatcher).checkDests\n\tknative.dev/serving/pkg/activator/net/revisio
n_backends.go:322\nknative.dev/serving/pkg/activator/net.(*revisionWatcher).run\n\tknative.dev/serving/pkg/activator/net/revision_backends.go:367"}

**Comment by evankanderson** [comment]
@JRBANCEL @arturenault

**Comment by a7i** [comment]
What was the resolution to this?

**Comment by jordanbecketmoore** [comment]
I am also looking for a resolution to this.
