### ISSUE TITLE
Remove sidecar injection "false" from networking-istio

### ISSUE THREAD

**Issue by nak3** [knative-sandbox/net-istio#615]
This is not serious issue but the following `sidecar.istio.io/inject: "false"` should be able to drop now:

https://github.com/knative-sandbox/net-istio/blob/383523e19f68b0dddde1de8ccdbf31b30336028d/config/controller.yaml#L31-L34

**Comment by DavidSpek** [comment]
@nak3 Could you maybe elaborate on why this can be dropped now?

**Comment by nak3** [comment]
The annotation was required for pod addressability as per https://github.com/knative/serving/pull/6413#issuecomment-570697144
But as far as I tested on my local, probe worked fine with injection now so I thought we could drop it. (But we still need to confirm if it can be really dropped. I just did a quick test.)
