### ISSUE TITLE
Allow namespace-less hostnames (when mesh is enabled)

### ISSUE THREAD

**Issue by julz** [knative-sandbox/net-istio#633]
Currently it is impossible for a Ksvc to curl a Ksvc in the same namespace without specifying the full namespace name in the URL (i.e. curl foo instead of curl foo.ns). This is unlike in raw Kubernetes where this works, and is because we need the namespace from the Host header to determine where to route the request (since Activator and Ingresses are shared and route at the HTTP rather than IP layer).

However when mesh is enabled the source namespace is available via the mtls certifacte information, and can be used by Istio's VirtualService via the [HTTPMatch sourceNamespace field](https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPMatchRequest). This should mean that we can create a VirtualService for the non-namespaced-hostname (i.e. foo rather than foo.ns) which _only_ matches for the sourceNamespace of the ksvc, and which adds the K_SERVING_NAMESPACE header to the request (so activator would just work).

This would allow users to curl services in the same namespace directly, just like in a normal kubernetes set-up.

**Comment by julz** [comment]
Related: https://github.com/knative/serving/issues/11340

**Comment by howardjohn** [comment]
One confusion I had - do you depend on the mtls certificate or not? It sounds like no with the sourceNamespace+added header.

My concern would be tying networking reachability to use of mtls. It may not be a big deal if everything is using mtls though.

Is there a concern about inconsistency of mesh vs non-mesh?

**Comment by julz** [comment]
Correct @howardjohn, I think this doesn't need the forwarded-client-cert since the mesh will add the header via the rule (I should have just avoided mentioning the cert, I didn't realise until I'd wrote it that we could do it all with sourceNamespace 😊).

Agree it's a shame for stuff to route differently in mesh vs non-mesh, I just don't know how to fix this in the non-mesh case. So the (very reasonable, I can see both arguments) question is do we prefer to have worse behaviour for everyone with mesh disabled to avoid a difference in behaviour between the cases?

**Comment by markusthoemmes** [comment]
Now I wonder if this can even work, seeing as Istio wouldn't know where to forward things :thinking:. Do the envoy routers even know what to do with `$svcName`? https://github.com/knative-sandbox/net-istio/issues/630 suggests that the gateways only know the namespace-qualified names anyway, so how would the requests even reach the activator?

**Comment by julz** [comment]
Not sure I follow @markusthoemmes. The destinations of the virtualservice would be the same as today, only there would be an extra HTTPMatch which matched the namespace-less hostname and required sourceNamespace. So where today we have a VS that looks like:

~~~~
..
		Retries: &istiov1alpha3.HTTPRetry{},
		Match: []*istiov1alpha3.HTTPMatchRequest{{
			Authority: &istiov1alpha3.StringMatch{
				MatchType: &istiov1alpha3.StringMatch_Prefix{Prefix: `test-route.test-ns`},
			},
			Gateways: []string{"mesh"},
		}},
		Route: []*istiov1alpha3.HTTPRouteDestination{{
			Destination: &istiov1alpha3.Destination{
				Host: "v2-service.test-ns.svc.cluster.local",
				Port: &istiov1alpha3.PortSelector{Number: 80},
			},
			Weight: 100,
			Headers: &istiov1alpha3.Headers{
			},
		}},
 ..                                                                                                                                                                                                                                                                                                                                                                                   
 },
~~~~

we would now have an additional one that looked like:

~~~~
..
		Retries: &istiov1alpha3.HTTPRetry{},
                 // Extra HTTPMatch for the short hostname that applies only with SourceNamespace matching ns suffix
		Match: []*istiov1alpha3.HTTPMatchRequest{{
                         SourceNamespace: "test-ns", // <-- THIS IS HOW WE KNOW WHERE TO ROUTE TO
			Authority: &istiov1alpha3.StringMatch{
			  MatchType: &istiov1alpha3.StringMatch_Prefix{Prefix: `test-route`}, // <-- THIS IS THE SHORT HOSTNAME
			},
			Gateways: []string{"mesh"},
		}},
		Route: []*istiov1alpha3.HTTPRouteDestination{{  // <-- DESTINATION UNMODIFIED..
			Destination: &istiov1alpha3.Destination{
				Host: "v2-service.test-ns.svc.cluster.local",
				Port: &istiov1alpha3.PortSelector{Number: 80},
			},
			Weight: 100,
			Headers: &istiov1alpha3.Headers{
                             "K-SERVING-NAMESPACE": "test-ns",   // <-- THIS IS HOW ACTIVATOR WORKS
			},
		}},
 ..                                                                                                                                                                                                                                                                                                                                                                                   
 },
~~~~

**Comment by markusthoemmes** [comment]
Yeah we should try really. My fear is that we don't even reach these matchers because the "top-level" `Host` doesn't match anything useful. That's just theoretic though, Dr. Empirical will tell.

**Comment by dprotaso** [comment]
So we technically have a top level K8s service for the Knative Service - via the Route.

It was originally there to "program Istio" - https://github.com/knative/serving/blame/c423d611816a414cb2d772b6482ff794991543d6/pkg/controller/elaservice/ela_service.go

Which I think meant the following cluster local services
`helloworld-test-image` 
`helloworld-test-image.svc` 
`helloworld-test-image.svc.cluster.local`

would resolve to the external name and thus get all the routing rules applies by istio

This existed prior to the Kingress separation. I now wonder if it's still necessary since we're programming the Kingress's with the cluster.local rules. 

Thus I wonder if we could repurpose this placeholder service and have them point at the ingress proxy pods which might make namespace to namespace working again

example placeholder service
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    serving.knative.dev/creator: dprotasowski@vmware.com
    serving.knative.dev/lastModifier: dprotasowski@vmware.com
  creationTimestamp: "2021-06-04T01:34:21Z"
  labels:
    serving.knative.dev/route: helloworld-test-image
    serving.knative.dev/service: helloworld-test-image
  name: helloworld-test-image
  namespace: default
  ownerReferences:
  - apiVersion: serving.knative.dev/v1
    blockOwnerDeletion: true
    controller: true
    kind: Route
    name: helloworld-test-image
    uid: 563d51f9-4bd7-4a71-b5d2-05212f2a5a54
  resourceVersion: "65278"
  selfLink: /api/v1/namespaces/default/services/helloworld-test-image
  uid: 4372125a-17ae-48df-918a-3624f8aca824
spec:
  externalName: helloworld-test-image.default.example.com
  ports:
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: ExternalName
status:
  loadBalancer: {}
```

**Comment by dprotaso** [comment]
Following up I realize the external name eventually changes to point to the internal k8s service fronting the ingress proxies

ie. for contour it's `envoy.contour-internal.svc.cluster.local`

So in the non-mesh case this works as expected
