### ISSUE TITLE
Envoy External Address Reported Incorrectly For Domain Mappings

### ISSUE THREAD

**Issue by diarmuidie** [knative-sandbox/net-istio#740]
When using a domain mapping with a Knative app Envoy incorrectly reports the Ingressgateway pod IP as the remote IP address:

**Expected Behaviour:**
The `x-envoy-external-address` in requests contains the correct external IP address of the requester when using a domain mapping domain.

**Actual Behaviour:**
The `x-envoy-external-address` contains the IP address of the Istio Ingress Gateway Pod.

For example here are the headers received by an app when accessed using a Domain Mapping Domain:
```
x-envoy-external-address: 10.60.xx.xx
x-forwarded-for: 84.203.xx.xx,10.50.xx.xx, 10.60.xx.xx
```
Where `84.203.xx.xx` is the correct external address, `10.60.xx.xx` is the IP address of the Istio Ingressgateway pod and `10.50.xx.xx` is the IP of the node that the Istio Ingressgateway is on.

It works correctly if I don't use the domain mapping and use the Knative apps default domain:
```
x-envoy-external-address: 84.203.xx.xx
x-forwarded-for: 84.203.xx.xx, 10.60.xx.xx
```

Tested on:
Knative 1.23.1
Net-Istio 1.23.1
Istio 1.9.7

**Comment by julz** [comment]
Hi @diarmuidie thanks for the report! I think this makes sense, given how domain mapping is currently implemented (there's an extra hop involved via the cluster-local ingress, at least in the istio implementation). Can you say a bit more about why you need to use x-envoy-external-address rather than x-forwarded-for for your use case?

**Comment by diarmuidie** [comment]
Hi @julz,

Ya, there are two problems this present for my use case. One is that by default the envoy logs report the incorrect IP. That's not a huge deal and we can work around it by using the x-forwarded-for like you say

The other is that because of the internal redirect the `x-forwarded-proto` header ends up being incorrect:

With domain mapping connected over HTTPS
```
      "x-forwarded-proto": "http" <--- this should be https
```

Without Domain Mapping over HTTPS
```
      "x-forwarded-proto": "https",
```

Because of that extra hop that the domain mapping makes Envoy thinks every domain mapping connection was originally over HTTP. The normal work around to this is to tell Envoy how many trusted proxies are in front of it using `xff_num_trusted_hops`, but because this number varies depending on if you're on the first or the extra hop and if there is a domain mapping in use or not it won't solve this case.

Hope that makes sense. Let me know if you need additional debug or info about this use case!

**Comment by julz** [comment]
Yeah, wonder if we could bump xff_num_trusted_hops in the domain mapping somehow 🤔

**Comment by 7adietri** [comment]
> With domain mapping connected over HTTPS
> 
> ```
>       "x-forwarded-proto": "http" <--- this should be https
> ```
> 
> Without Domain Mapping over HTTPS
> 
> ```
>       "x-forwarded-proto": "https",
> ```

This is quite a problem for us too, because (as far as I can tell) logic in i.e. [flask.Request](https://flask.palletsprojects.com/en/2.0.x/api/#flask.Request.is_secure) now thinks the requests are insecure and we check for that.
