### ISSUE TITLE
Deprecation warnings for HorizontalPodAutoscaler and PodDisruptionBudget

### ISSUE THREAD

**Issue by psschwei** [knative-sandbox/net-istio#869]
I was [installing Istio](https://knative.dev/docs/install/serving/install-serving-with-yaml/#install-a-networking-layer) on a local k8s v1.22 cluster and got the following warnings during the install:

`Warning: autoscaling/v2beta1 HorizontalPodAutoscaler is deprecated in v1.22+, unavailable in v1.25+; use autoscaling/v2beta2 HorizontalPodAutoscaler`
`Warning: policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget`

Based on a quick glance, looks like it's an upstream istio issue (all the results I found were in `third-party/istio-latest` or `third-party/istio-head`), but just in case figured I'd open an issue here.

**Comment by nak3** [comment]
Yes, I agree that it is an upstream issue. And I found https://github.com/istio/istio/issues/34479 is fixing it.

**Comment by psschwei** [comment]
Closing since it's an upstream issue
