### ISSUE TITLE
istio-head manifest does not track `HEAD` automatically

### ISSUE THREAD

**Issue by nak3** [knative-sandbox/net-istio#913]
`istio-head` downloads the nightly Istio build for test. However, the manifest under `third_party/istio-head/` needs manual update and so it is usually obsolete.

There are some idea to solve:

- Bump to some notable pre-release and not HEAD - ie. bump to a latest nightly release on a Friday. see - https://github.com/knative-sandbox/net-istio/pull/828#issuecomment-987389647
- Let update-deps bot like this PR https://github.com/knative-sandbox/net-istio/pull/911 bump the Istio head manifest.
- Do not keep the HEAD manifest under `third_party/istio-head/` - i.e. [e2e-networking-library.sh](https://github.com/knative/serving/blob/release-1.4/test/e2e-networking-library.sh) should install Istio by `istioctl install` instead of the yaml.

... etc

**Comment by nak3** [comment]
> Let update-deps bot like this PR https://github.com/knative-sandbox/net-istio/pull/911 bump the Istio head manifest.

knbots send the PR every 12 hours when there is a diff - https://github.com/knative-sandbox/knobots/blob/f3e8c0588c8e815a0d3100eccaafa6fca2948ce2/.github/workflows/auto-update-deps.yaml#L24
So, it is too frequent to bump the istio head.

**Comment by AngeloDanducci** [comment]
Sounds like we don't want to use knbot for all new head changes.

What do you see the pros/cons of notable pre release vs using the networking library to run istioctl install?

I vaguely remember the community moving away from istioctl install in favor of yaml.  Any thoughts on this @dprotaso ?

**Comment by nak3** [comment]
Actually istio-head was dropped by https://github.com/knative-sandbox/net-istio/pull/1053 so let's close this.
